# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af91d7ecd9bbc04982efe007651fba32"
name = "beefly-app"
handle = "beefly-app"
application_url = "https://beefly-563442940248.us-central1.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "beefly-onboarding-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,read_orders,write_metaobject_definitions,write_metaobjects,write_orders"

[auth]
redirect_urls = [
  "https://beefly-563442940248.us-central1.run.app/api/auth"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[pos]
embedded = false
